### ISSUE TITLE
Failed to detect set buildpack, in subdir of repo?

### ISSUE THREAD

**Issue by laduke** [srid/heroku-buildpack-elm#15]
Hi, 
I had this buildpack working, then I put my elm folder into a phoenix app at ./web/elm. I builds locally, but heroku doesn't like it. How do I debug?

λ heroku buildpacks

> === xxx-cliffs-33134 Buildpack URLs
> 1. https://github.com/HashNuke/heroku-buildpack-elixir.git
> 2. https://github.com/srid/heroku-buildpack-elm.git
> 3. https://github.com/gjaldon/heroku-buildpack-phoenix-static.git

git push heroku master

> remote: -----> Fetching set buildpack https://github.com/srid/heroku-buildpack-elm.git... done  
> remote:  !     Push rejected, failed to detect set buildpack https://github.com/srid/heroku-buildpack-elm.git  
> remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure  
> remote: Verifying deploy....  
> remote: ! Push rejected to xxx-cliffs-33134.  
> To https://git.heroku.com/xxx-cliffs-33134.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/xxx-cliffs-33134.git

**Comment by anicholson** [comment]
Hi @laduke,

Happy to help if I can.
Can you post your `app.json` here?

**Comment by laduke** [comment]
"https://github.com/laduke/elm-experiment" doesn't exist anymore. Hope that isn't it. 
I've tried it with the static buildpack removed, but this is what I started with. 

```
{
    "name": "Playlist test in Elm",
    "repository": "https://github.com/laduke/elm-experiment",
    "env": {
        "ELM_COMPILE": "elm-make Main.elm --output=elm.js"
    },
    "buildpacks": [
        {
            "url": "https://github.com/srid/heroku-buildpack-elm.git"
        },
        {
            "url": "https://github.com/hone/heroku-buildpack-static"
        }

    ]
}
```

**Comment by laduke** [comment]
It looks like (obviously) there's more too it than just moving a directory and assuming it will work. I found this: https://github.com/joshuaclayton/phoenix_elm_webpack_heroku_example_app haven't got it working yet.

**Comment by anicholson** [comment]
Your "ELM_COMPILE" config variable has to correctly reference the right paths in the file-system. Does it work if you fully-qualify the relative path to `Main.elm`?
