### ISSUE TITLE
Upgrade elm to 0.17.1

### ISSUE THREAD

**Issue by pinx** [srid/heroku-buildpack-elm#19]
For my project, I need this version. I tried to "make binaries" but it complains about the docker daemon. Docker seems installed fine, though.
Can someone do this, and put the version on S3?

**Comment by srid** [comment]
I will look at it. For docker, you might want to try 'sudo make binaries' on Linux.

**Comment by pinx** [comment]
Of course, "sudo", why didn't I think of that? Thanks. Still more hurdles to take, like uploading to S3, so I hope you can do all this. Would be a big challenge for me.

**Comment by srid** [comment]
This is now done; let me know if it doesn't work.

Also - https://github.com/srid/heroku-buildpack-elm/commit/eda47890bc1bd1dc60ac8186b932dcedfa6ed197
