### ISSUE TITLE
Any way to run custom servers?

### ISSUE THREAD

**Issue by jinjor** [srid/heroku-buildpack-elm#2]
Hi,
I started using this buildpack and like it very much.

Now I'm facing a problem while running a custom server.
In my project, I use Node.js server to provide dynamic contents.
So I need a way for it instead of setting `ELM_STATIC_DIR`.

Also, I use two buildpacks.
Which ordering do you think is easier to deploy, Node.js first or Elm first?

**Comment by srid** [comment]
@jinjor - sorry for the delayed response; for some reason I get no email notifications for issues filed on my own git repos. :-/

> running a custom server

The buildpack [currently uses](https://github.com/srid/heroku-buildpack-elm/blob/master/bin/compile#L50) warp and spas (downloaded from s3) for run the web server, so they are hardcoded. Specifying a custom server is not easy unless you want to include a Linux64 binary of it in the git repo. Perhaps we can extend this buildpack to support a custom ELM_STATIC_SERVER_BINARY_URL environment variable (typically a s3 url) where this custom binary can be downloaded from?

>  I use two build packs.
> Which ordering do you think is easier to deploy, Node.js first or Elm first?

Best to do it all part of the same deployment process. Also checkout https://github.com/ddollar/heroku-buildpack-multi

**Comment by srid** [comment]
I think you may just be able to get it working with heroku-buildpack-multi after specifying the full command-line in a custom `Procfile` (my buildpack auto-generates the Profile only if it doesn't already exist).

**Comment by jinjor** [comment]
Thanks! (and sorry for long absence)

I wrote a custom `Procfile` and it works successfully ;)

**Comment by srid** [comment]
@jinjor I just made it easier to use custom web servers in #6
